language: cpp

compiler: gcc

before_install:
    - sudo apt-get update -qq

# NB: this below list must be kept in sync with `README.md`
install:
    - sudo apt-get install -qq build-essential cmake
    - sudo apt-get install -qq libsdl2-dev
    - sudo apt-get install -qq libsdl-image1.2-dev
    - sudo apt-get install -qq libepoxy
    - sudo apt-get install -qq libassimp-dev
    - sudo apt-get install -qq libglm-dev
    - sudo apt-get install -qq ilibbullet-dev

script:
    - make clean
    - cmake .
    - make
    - make test

