language: cpp

compiler: gcc

before_install:
    # http://www.ubuntuupdates.org/ppa/getdeb_games for libbullet-dev >= 2.7
    - wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
    - sudo sh -c 'echo "deb http://archive.getdeb.net/ubuntu precise-getdeb games" > /etc/apt/sources.list.d/getdeb.list'
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots # libsdl2-dev, libsdl2-image-dev
    - sudo apt-add-repository -y ppa:sfttech/random # libepoxy-dev
    - sudo apt-get update -qq

# NB: this below list must be kept in sync with `README.md`
install:
    - sudo apt-get install -qq build-essential cmake
    - sudo apt-get install -qq libsdl2-dev
    - sudo apt-get install -qq libsdl2-image-dev
    - sudo apt-get install -qq libepoxy-dev
    - sudo apt-get install -qq libassimp-dev
    - sudo apt-get install -qq libglm-dev
    - sudo apt-get install -qq libbullet-dev

script:
    - apt-cache policy libassimp-dev libc6 libgcc1 libstdc++6 zlib1g
    - cmake .
    - make
    - make test

