dist: trusty
sudo: required

language: cpp

compiler: gcc

git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:zoogie/sdl2-snapshots'
        packages:
        - libconfig-dev
        - gcc-5
        - g++-5
        - libsdl2-dev
        - libsdl2-image-dev
        - libepoxy-dev
        - libbullet-dev
        - libfreetype6-dev
        - libassimp-dev
        - cmake

# NB: this below list must be kept in sync with `README.md`
install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
    - cmake .
    - make -sk
    - make test

